#!/usr/bin/env bash

DIR=""

case $# in
0) DIR="$PWD" ;;
1) DIR="$1" ;;
*)
    echo "Zero or One path argument is expected!"
    exit 1
    ;;
esac

echo "$DIR"

# TODO: Add git-dir check
#if ! git rev-parse --git-dir -C "$DIR" >/dev/null 2>&1; then
#    echo "Not in a git-versioned directory!"
#    exit 1
#else
#    echo "ok"
#fi

git status --untracked-files=no --ignored=no --porcelain -- "$DIR" | ./script.py
